/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eq.point.of.sale.system;

import eq.point.of.sale.system.Queries.AddStocks;
import static eq.point.of.sale.system.Queries.AddStocks.rs;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Diowinard Medrano
 */
public class frmAddStocksLog extends javax.swing.JPanel {

  static String Jaction;

    AddStocks db = new AddStocks("localhost", "eqpos", "root", "");
    

    /**
     * Creates new form frmStocksLog
     */
    public frmAddStocksLog() {
        initComponents();

        GetAccounts();
        curtime();
        curdate();
     setJdate();
        
    }

    public final void GetAccounts() {
        cbAdmins.removeAllItems();
        try {
            db.Open();
            db.SelectAccounts();
            while (rs.next()) {
                cbAdmins.addItem(rs.getString(1) + " " + rs.getString(2));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void setJdate(){
        Date date=new Date();
        DateLogs.setDate(date);
    }

    @SuppressWarnings("empty-statement")

//    private int hour, minute, second;
    private void curtime() {
//        hour = ((h >= 0 && h < 24) ? h : 0);
//        minute = ((m >= 0 && m < 60) ? m : 0);
//        second = ((s >= 0 && s < 60) ? s : 0);
        try {
            db.Open();
            db.CurrentTime();
            if (rs.next()) {

                String Time = rs.getString(1);

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    private void curdate() {
        try {
            db.Open();
            db.CurrentDate();

            if (rs.next()) {

                String Date = rs.getString(1);

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtextLogs = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbAdmins = new javax.swing.JComboBox<>();
        JAction = new javax.swing.JComboBox<>();
        DateLogs = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DateLogs1 = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 35));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(0, 35));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(35, 789));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JtextLogs.setEditable(false);
        JtextLogs.setColumns(20);
        JtextLogs.setRows(5);
        JtextLogs.setDragEnabled(true);
        jScrollPane2.setViewportView(JtextLogs);

        jLabel1.setText("PRODUCT DISTRIBUTOR--------PRODUCT NAME--------UNIT OF MEASURE--------QUANTITY--------SIZE--------SECTION--------ACCESSORIES--------COLOR--UNIT PRICE");

        jPanel2.setPreferredSize(new java.awt.Dimension(0, 35));

        cbAdmins.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cbAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAdminsActionPerformed(evt);
            }
        });

        JAction.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        JAction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--", "Logs for ADDING Products", "Logs for UPDATING Products", "Logs for DELETING", "Logs for ADDING STOCKS" }));
        JAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JActionActionPerformed(evt);
            }
        });

        DateLogs.setDateFormatString("yyyy-MM-dd");
        DateLogs.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("User:");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("From Date:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("To Date:");

        DateLogs1.setDateFormatString("yyyy-MM-dd");
        DateLogs1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JAction, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAdmins, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateLogs, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateLogs1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbAdmins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(DateLogs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(DateLogs1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAdminsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAdminsActionPerformed

    private void JActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JActionActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(DateLogs.getDate());
        JtextLogs.setText("");
        System.out.println(rs);
        if (JAction.getSelectedIndex() == 1) {
         
            try {
                db.Open();
                db.addLog(date);
               
                while (rs.next()) {
                    String user = rs.getString("user");
                    String Product_Name = rs.getString("Product_Name");
                    String Quantity = rs.getString("Quantity");
                    String Time = rs.getString("Time");
                    String Date = rs.getString("Date");
                   JtextLogs.append(user + " Added the new Product " + Product_Name + " \t\t\t " + Time + "\t" + Date + "\n ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n");
                 
                    

                }
               
                db.Close();
            } catch (SQLException e) {
            }
        } else if (JAction.getSelectedIndex() == 2) {
 
            try {
                db.Open();
                db.updateLog(date);
                while (rs.next()) {
                    String user = rs.getString("user");

                    String Product_Distributor = rs.getString("Supplier_ID");
                    String Product_Name = rs.getString("Product_Name");
//                    String Description = rs.getString("Description");
                    String UnitOfMeasure = rs.getString("UnitOfMeasure");
                    String Quantity = rs.getString("Quantity");
                    String Size = rs.getString("Size");
                    String Section = rs.getString("Category_ID");
                    String Accessories = rs.getString("SubCategory_ID");
                    String Color = rs.getString("Color_ID");
                    double UnitPrice = rs.getDouble("Unit_Price");
                    String Time = rs.getString("Time");
                    String Date = rs.getString("Date");
                  JtextLogs.append(user + " Updated the Product " + Product_Name + " \t\t\t" + Time + "\t" + Date + "\n\n TO:   " + Product_Distributor + "   " + Product_Name + "    " + UnitOfMeasure + "    " + Quantity + "    " + Size + "    " + Section + "    " + Accessories + "    " + Color + "    " + UnitPrice + "\n\t\n--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n");

                }
                db.Close();
            } catch (SQLException e) {
            }
        } else if (JAction.getSelectedIndex() == 3) {
 
            try {
                db.Open();
                db.deleteLog(date);
                while (rs.next()) {
                    String user = rs.getString("user");
                    String Product_Name = rs.getString("Product_Name");
                    String Quantity = rs.getString("Quantity");
                    String Time = rs.getString("Time");
                    String Date = rs.getString("Date");
                    JtextLogs.append(user + " Deleted the Product " + Product_Name + " \t\t\t" + Time + "\t" + Date + "\n ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n");
                }
                db.Close();
            } catch (SQLException e) {
            }

        } else if (JAction.getSelectedIndex() == 4) {

            try {
                db.Open();
                db.AddStockLog(date);

                while (rs.next()) {
                    String user = rs.getString("user");
                    String Product_Name = rs.getString("Product_Name");
                    String EnterQuantity = rs.getString("EnterQuantity");

                    String Time = rs.getString("Time");
                    String Date = rs.getString("Date");
//                   
                    JtextLogs.append(user + " Added  " + EnterQuantity + " Quantity of " + " Product " + Product_Name + "\t\t" + Time + "\t" + Date + "\n ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n");
                }
                db.Close();
            } catch (SQLException e) {
            }
        }

    }//GEN-LAST:event_JActionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateLogs;
    private com.toedter.calendar.JDateChooser DateLogs1;
    public static javax.swing.JComboBox<String> JAction;
    public static javax.swing.JTextArea JtextLogs;
    private javax.swing.JComboBox<String> cbAdmins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
