/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eq.point.of.sale.system;

import eq.point.of.sale.system.DBConnection.DBConnection;
import eq.point.of.sale.system.Queries.PointOfSale;
import static eq.point.of.sale.system.Queries.PointOfSale.rs;
import static eq.point.of.sale.system.frmUserManagement.btnCreate;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author billy
 */
public class frmMain extends javax.swing.JFrame {

    DBConnection DBCon = new DBConnection("localhost", "3306", "eqpos", "root", "001995234");
    //PointOfSale db = new PointOfSale("localhost", "eqpos", "root", "2001995234");
    frmPointOfSale POS = new frmPointOfSale();
    frmStocks Stocks = new frmStocks();
    frmUserManagement UserManagement = new frmUserManagement();
    frmCustomers Customers = new frmCustomers();
    frmSupplier Supplier = new frmSupplier();
    frmReport Report = new frmReport();

    /**
     * Creates new form frmMain
     *
     */
    public frmMain() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        Middle.add(POS);
        Middle.add(Stocks);
        Middle.add(Customers);
        Middle.add(UserManagement);
        Middle.add(Supplier);
        Middle.add(Report);
        POS.setVisible(true);

//        Stocks.setVisible(false);
//        Customers.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Top = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnStocks = new javax.swing.JButton();
        btnPointOfSale = new javax.swing.JButton();
        btnUserManagement = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnSignout = new javax.swing.JButton();
        btnCustomers = new javax.swing.JButton();
        btnCustomers1 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        Middle = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Top.setBackground(new java.awt.Color(255, 255, 255));

        btnStocks.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnStocks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemIcons/Stocks.png"))); // NOI18N
        btnStocks.setText("STOCKS");
        btnStocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStocksActionPerformed(evt);
            }
        });

        btnPointOfSale.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnPointOfSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemIcons/Cashier.png"))); // NOI18N
        btnPointOfSale.setText("POINT OF SALE");
        btnPointOfSale.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPointOfSale.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPointOfSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPointOfSaleActionPerformed(evt);
            }
        });

        btnUserManagement.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnUserManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemIcons/UserManagement.png"))); // NOI18N
        btnUserManagement.setText("USER MANAGEMENT");
        btnUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagementActionPerformed(evt);
            }
        });

        btnReport.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemIcons/Report.png"))); // NOI18N
        btnReport.setText("REPORT");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnSignout.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnSignout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemIcons/Signout.png"))); // NOI18N
        btnSignout.setText("SIGNOUT");
        btnSignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignoutActionPerformed(evt);
            }
        });

        btnCustomers.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemIcons/Customers.png"))); // NOI18N
        btnCustomers.setText("CUSTOMERS");
        btnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersActionPerformed(evt);
            }
        });

        btnCustomers1.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnCustomers1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemIcons/Customers.png"))); // NOI18N
        btnCustomers1.setText("SUPPLIER");
        btnCustomers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomers1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPointOfSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStocks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUserManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCustomers1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSignout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPointOfSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStocks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUserManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSignout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCustomers1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemIcons/Exit.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome");

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(TopLayout.createSequentialGroup()
                        .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLayout.createSequentialGroup()
                .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(Top, java.awt.BorderLayout.PAGE_START);

        Middle.setBackground(new java.awt.Color(255, 255, 255));
        Middle.setLayout(new java.awt.CardLayout());
        getContentPane().add(Middle, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStocksActionPerformed
        // TODO add your handling code here:
        POS.setVisible(false);
        Customers.setVisible(false);
        Stocks.Clear();
        Stocks.RefreshProducts();
        Stocks.cbSubCategory.removeAllItems();
        Stocks.cbColor.removeAllItems();
        Stocks.lblCategory.setText("");
        Stocks.btnAddQuantity.setEnabled(false);
        Stocks.btnSubtractQuantity.setEnabled(false);
        Stocks.btnAddSubCat.setEnabled(false);
        Stocks.btnDeleteSubCat.setEnabled(false);
        Stocks.setVisible(true);
        UserManagement.setVisible(false);
        Supplier.setVisible(false);
    }//GEN-LAST:event_btnStocksActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new frmLogin().setVisible(true);
    }//GEN-LAST:event_btnSignoutActionPerformed

    private void btnPointOfSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPointOfSaleActionPerformed
        // TODO add your handling code here:

        POS.cbCustomers.removeAllItems();
        POS.GetCustomers();
        POS.setVisible(true);
        Stocks.setVisible(false);
        Customers.setVisible(false);
        UserManagement.setVisible(false);
        Supplier.setVisible(false);
        POS.cbCustomers.setSelectedIndex(-1);

    }//GEN-LAST:event_btnPointOfSaleActionPerformed

    private void btnUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagementActionPerformed
        // TODO add your handling code here:
        if (frmLogin.AccessType.equals("Cashier")) {
            POS.setVisible(false);
            Stocks.setVisible(false);
            Customers.setVisible(false);
            UserManagement.setVisible(true);
            Supplier.setVisible(false);
            UserManagement.RefreshUser();
        } else if (frmLogin.AccessType.equals("Sales Rep")) {
            POS.setVisible(false);
            Stocks.setVisible(false);
            Customers.setVisible(false);
            UserManagement.setVisible(true);
            UserManagement.RefreshUser1();
            UserManagement.btnCreate.setEnabled(false);
            Supplier.setVisible(false);
        }
    }//GEN-LAST:event_btnUserManagementActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        JOptionPane.showMessageDialog(null, "UNDER DEVELOPMENT");
//        POS.GetCustomers();
//        POS.setVisible(false);
//        Stocks.setVisible(false);
//        Customers.setVisible(false);
//        UserManagement.setVisible(false);
//        Supplier.setVisible(false);
//         Report.setVisible(true);
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        // TODO add your handling code here:
        POS.setVisible(false);
        Stocks.setVisible(false);
        Customers.setVisible(true);
        UserManagement.setVisible(false);
        Supplier.setVisible(false);
        Customers.RefreshCustomer();
    }//GEN-LAST:event_btnCustomersActionPerformed

    private void btnCustomers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomers1ActionPerformed
        // TODO add your handling code here:
        POS.setVisible(false);
        Stocks.setVisible(false);
        Customers.setVisible(false);
        UserManagement.setVisible(false);
        Supplier.setVisible(true);
        Supplier.RefreshSupplier();
        Supplier.JTableSupplier();
    }//GEN-LAST:event_btnCustomers1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Middle;
    private javax.swing.JPanel Top;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnCustomers1;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPointOfSale;
    public static javax.swing.JButton btnReport;
    private javax.swing.JButton btnSignout;
    private javax.swing.JButton btnStocks;
    public static javax.swing.JButton btnUserManagement;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables

}
