/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eq.point.of.sale.system;

import static eq.point.of.sale.system.Queries.PointOfSale.rs;
import eq.point.of.sale.system.Queries.PointOfSale;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Diowinard Medrano
 */
public class frmPayLogs extends javax.swing.JPanel {

    PointOfSale db = new PointOfSale("localhost", "eqpos", "root", "");

    /**
     * Creates new form frmPayLogs
     */
    public frmPayLogs() {
        initComponents();

        GetAccounts();

//        curtime();
//        curdate();
        setJdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cbCustomer = new javax.swing.JComboBox<>();
        jDateChooserFrom = new com.toedter.calendar.JDateChooser();
        jDateChooserTo = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jDateChooserFrom.setDateFormatString("yyyy-MM-dd");

        jDateChooserTo.setDateFormatString("yyyy-MM-dd");

        jLabel1.setText("FROM");

        jLabel2.setText("TO");

        jButton1.setText("Search ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(cbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(cbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jDateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jButton1)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fromDate = sdf.format(jDateChooserFrom.getDate());
        String toDate = sdf.format(jDateChooserTo.getDate());
        jTextArea1.setText("");
        String Customer = cbCustomer.getSelectedItem().toString();

        try {
            db.Open();
            db.RangeSearch(Customer, fromDate, toDate);

            while (rs.next()) {

                String user = rs.getString("user");
                String customer = rs.getString("customer");

                String cash = rs.getString("cash_gave");
                String cost = rs.getString("cost");
                String changed = rs.getString("changed");
                String products = rs.getString("products");
                String qty = rs.getString("quantity");
                String time = rs.getString("time");
                String dates = rs.getString("date");
                jTextArea1.append(user + " sold the  Product/s  to  " + customer + "\tCost:(" + cost + ")\n\n");
                jTextArea1.append("(" + qty + ") " + products + "\t" + time + "\t" + dates + "\n");
                jTextArea1.append("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n\n");
            }

            db.Close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        try {
            db.Open();
            db.RangeSearch(Customer, fromDate, toDate);

            while (rs.next()) {

                String customer = rs.getString("customer");

                String cash = rs.getString("cash_gave");
                String cost = rs.getString("cost");
                String changed = rs.getString("changed");
                String products = rs.getString("products");
                String qty = rs.getString("quantity");
                String time = rs.getString("time");
                String dates = rs.getString("date");
//                jTextArea1.append(user + " Sold the following Products to " + customer + ":\n\n" + "Cash:  " + cash + " Cost:  " + cost + " Change:  " + changed + "\n\n");
//                jTextArea1.append("(" + qty + ") " + products + "\tCost: " + "(" + cost + ")" + "\t\t" + time + "\t" + dates + "\n");
            }

            db.Close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    public final void GetAccounts() {
        cbCustomer.removeAllItems();
        try {
            db.Open();
            db.SelectCustomers();
            while (rs.next()) {
                cbCustomer.addItem(rs.getString(1) + " " + rs.getString(2));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void setJdate() {
        Date date = new Date();
        jDateChooserFrom.setDate(date);
        jDateChooserTo.setDate(date);
    }

    private void curtime() {

        try {
            db.Open();
            db.CurrentTime();
            if (rs.next()) {

                String Time = rs.getString(1);

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    private void curdate() {
        try {
            db.Open();
            db.CurrentDate();

            if (rs.next()) {

                String Date = rs.getString(1);

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCustomer;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooserFrom;
    private com.toedter.calendar.JDateChooser jDateChooserTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
